### ISSUE TITLE
海天报错

### ISSUE THREAD

**Issue by jiuchu** [darkbfly/ql#6]
Traceback (most recent call last):
File "/ql/scripts/ApiRequest.py", line 41, in run
getattr(request(i), func)()
File "/ql/scripts/htmwg.py", line 42, in login
response = self.sec.post('https://cmallapi.haday.cn/buyer-api/sign/activity/sign', json=data)
File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 577, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
r = adapter.send(request, **kwargs)
File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cmallapi.haday.cn', port=443): Max retries exceeded with url: /buyer-api/sign/activity/sign (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -2] Name does not resolve'))

**Comment by darkbfly** [comment]
这个应该是你的网络问题 域名解析失败
